Add redhat-rpm-config package into the Containerfile
To avoid issues like:

    specfile.exceptions.RPMException: invalid syntax in lua scriptlet: [string "%postun"]:10: unexpected symbol near '%'

when building the gcc package, which is caused by missing `lua-srpm-macros` package.

Because there are more `*-srpm-macros` packages out there, I'm adding the `redhat-rpm-config` that requires them, instead of adding each of them individually.